### ISSUE TITLE
mixsqp can return (numerically) negative values

### ISSUE THREAD

**Issue by willwerscheid** [stephenslab/mixsqp#25]
For example, set `L` and `pi_init` as in the attached files with all weights set to 1. Negative values wreak havoc with `ashr` (calculating posterior means, etc.), so I think they should be thresholded out.
[bad.zip](https://github.com/stephenslab/mixsqp/files/2848390/bad.zip)

**Comment by pcarbo** [comment]
Thanks @willwerscheid. I will take a look.

**Comment by pcarbo** [comment]
@willwerscheid This is my code:

```R
library(mixsqp)
x0  <- readRDS("badpiinit.rds")
L   <- readRDS("badA.rds")
out <- mixsqp(L,x0 = x0)
print(out$x,digits = 2)
```

And this is what I got:

```
iter        objective max(rdual) nnz stepsize max.diff nqp nls
   1 +1.094065997e-04 +8.603e-05   8       NA       NA  NA  NA
   2 +2.338687910e-05 +2.564e-09   1 1.00e+00 1.42e-02   9   1
Convergence criteria met---optimal solution found.
[1]  1.0e+00 -2.8e-17  0.0e+00  0.0e+00  0.0e+00  0.0e+00  0.0e+00  0.0e+00
```

Did you get the same result?

**Comment by willwerscheid** [comment]
@pcarbo Yes, the same. It's that second mixture component (-2.8e-17) that causes problems for `ashr` (pms and psds are all `NaN`). I think it's because there are logs somewhere and we've handled zeros but not negative values, but I haven't looked carefully. We could of course change the handling in `ashr` but I imagine it would be much easier to just threshold out zero results in `mixsqp`.

**Comment by pcarbo** [comment]
@willwerscheid Try this:

```R
library(mixsqp)
x0  <- readRDS("badpiinit.rds")
L   <- readRDS("badA.rds")
out <- mixsqp(L,x0 = x0,control = list(eps = 0))
print(out$x,digits = 2)
```

So that is one possible solution.

I agree that we should take an additional step to ensure that the iterates are always positive; this could be done I suppose with a simple [simplex projection](https://www.cs.ubc.ca/~schmidtm/Software/minConf.html) in the backtracking line search. This happens only in cases when `eps > 0`, because in this case the `log(x + eps)` acts a "barrier" to push x away from `-eps`, not zero. However, implementing this change, although relatively straightforward, could cause some unanticipated tissues, so I will leave this issue open.

In the meantime, I suggest correcting the solution thresholding then re-normalizing.

**Comment by pcarbo** [comment]
@willwerscheid In your example (above), I now get this:

```
> out <- mixsqp(L,x0 = x0)
Running mix-SQP algorithm 0.1-104 on 494 x 8 matrix
convergence tol. (SQP):     1.0e-08
conv. tol. (active-set):    1.0e-10
zero threshold (solution):  1.0e-06
zero thresh. (search dir.): 1.0e-08
l.s. sufficient decrease:   1.0e-02
step size reduction factor: 5.0e-01
minimum step size:          1.0e-04
max. iter (SQP):            1000
max. iter (active-set):     9
iter        objective max(rdual) nnz stepsize max.diff nqp nls
   1 +1.094065997e-04 +8.603e-05   8       NA       NA  NA  NA
   2 +6.639518160e-05 +4.301e-05   8 5.00e-01 7.09e-03   9   2
   3 +2.337753078e-05 -6.785e-09   1 1.00e+00 7.09e-03   9   1
Convergence criteria met---optimal solution found.
> print(out$x,digits = 2)
[1] 1 0 0 0 0 0 0 0
```
