### ISSUE TITLE
Suggestion for documentation

### ISSUE THREAD

**Issue by willwerscheid** [stephenslab/mixsqp#26]
I would suggest including the default values for the control parameters in the docs for `mixsqp`. For example, when I am told that optimization has not converged and that I should increase `maxiter`, it is not clear what I should set it to since I don't know what the current value is. (Also, it might be helpful to say whether you are talking about `maxiter.sqp` or `maxiter.activeset` or both.)

**Comment by pcarbo** [comment]
@willwerscheid From `help(mixsqp)`:

```
The ‘control’ argument is a list in which any of the following named components will override the default optimization algorithm settings (as they are defined by ‘mixsqp_control_defaults’).
```

Any suggestions for how this could be made more clear?

> Also, it might be helpful to say whether you are talking about `maxiter.sqp` or `maxiter.activeset` or both.

I will fix this.

**Comment by willwerscheid** [comment]
I did see that -- I was thinking of adding, e.g., "The default setting is 1000" or whatever to each of the parameters described but now that I think of it you can just type `mixsqp_control_defaults` to get the list of settings so maybe you can ignore this issue.

**Comment by pcarbo** [comment]
@willwerscheid Can you tell me exactly the message you are getting? I wonder if this is an older version of mixsqp; we might not report that message anymore.

> I was thinking of adding, e.g., "The default setting is 1000."

@willwerscheid The recommended practice is not to add the defaults to the roxygen2 since it is difficult to keep these defaults up-to-date, and they are already provided automatically after re-running `roxygen2::roxygenize()`. The exception is when the default is complicated, and therefore will require an explanation.

**Comment by willwerscheid** [comment]
My mistake! The message is coming from `estimate_mixprop` in `ashr`. We should probably change that message since there is no `maxiter` parameter there. Closing here.
