### ISSUE TITLE
irlba requires R >= 3.6.2

### ISSUE THREAD

**Issue by mcolosimo-p4** [stephenslab/mixsqp#47]
It seems in the last two months, https://github.com/bwlewis/irlba was updated to require R >= 3.6.2. You might want to either update your requirement or specify version "2.3.3' of irlba. I ran into this when installing a package that depends on mixsqp.

**Comment by pcarbo** [comment]
Hi @mcolosimo-p4 thanks for the feedback. We will let irlba impose this requirement rather than mixsqp. And unfortunately CRAN only allows "greater than equal to" version requirements, which will not address the issue you report. This is not an uncommon issue with package development, but not much we can do about it.
